# Generated by Django 3.1.8 on 2021-06-24 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Assigned_Employee',
            field=models.ManyToManyField(to='inventory_api.Employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory_api.role'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory_api.type')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=True)),
                ('date_returned', models.DateField(blank=True, default=None, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_api.employees')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_api.products')),
            ],
        ),
    ]
