# Generated by Django 3.1.8 on 2021-06-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0003_auto_20210624_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approval',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
