# Generated by Django 3.1.8 on 2021-06-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0004_request_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='inventory_api.employees'),
            preserve_default=False,
        ),
    ]
