# Generated by Django 3.1.8 on 2021-06-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0005_request_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory_api.producttype'),
        ),
    ]
