# Generated by Django 3.1.8 on 2021-06-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0006_auto_20210625_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Storefront',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory_api.storefront'),
        ),
    ]
