# Generated by Django 3.1.8 on 2021-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0007_auto_20210625_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
