# Generated by Django 3.1.8 on 2021-06-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0009_auto_20210626_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Assigned_Employee',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Storefront',
        ),
        migrations.RemoveField(
            model_name='products',
            name='model',
        ),
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='request',
            name='product',
        ),
        migrations.RemoveField(
            model_name='request',
            name='type',
        ),
        migrations.RemoveField(
            model_name='storefront',
            name='manager',
        ),
        migrations.DeleteModel(
            name='AssignedProducts',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Storefront',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
