# Generated by Django 3.1.8 on 2021-06-28 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0014_auto_20210627_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='access',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
