# Generated by Django 3.1.8 on 2021-06-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0015_requesttype_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=True)),
                ('date_removed', models.DateField(blank=True, default=None, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory_api.products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_api.storefront')),
            ],
        ),
    ]
