# Generated by Django 3.1.8 on 2021-06-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0017_delete_storeinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='returning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
